version: '3.7'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: petsaojoao_dev
      POSTGRES_PASSWORD: example
